[package]
name = "oidc-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.58"
clap = { version = "3.2.3", features = ["derive"] }
oauth2 = { version = "4.2.0", default-features = false, features = ["ureq"] }
